const canti = [
  {
    titolo: 'Gridate con Gioia',
    link:'https://www.cantineocatecumenale.it/precatecumenato/gridate-con-gioia/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Grazie a Jahvè',
    link:'https://www.cantineocatecumenale.it/precatecumenato/grazie-a-jahve/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: true,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Abramo',
    link:'https://www.cantineocatecumenale.it/precatecumenato/abramo/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Acclamate al Signore',
    link:'https://www.cantineocatecumenale.it/precatecumenato/acclamate-al-signore/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: true,
    pentecoste: false,
  },
  {
    titolo: 'Alzate o porte',
    link:'https://www.cantineocatecumenale.it/precatecumenato/alzate-o-porte/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Alzo gli occhi verso i monti',
    link:'https://www.cantineocatecumenale.it/precatecumenato/alzo-gli-occhi-verso-i-monti/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: true,
    pentecoste: false,
  },
  {
    titolo: 'Benedetta sei tu Maria',
    link:'https://www.cantineocatecumenale.it/precatecumenato/benedetta-sei-tu-maria/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: true,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Che belle sono le tue tende',
    link:'https://www.cantineocatecumenale.it/precatecumenato/che-belle-sono-le-tue-tende/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: false,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Chi ci separerà',
    link:'https://www.cantineocatecumenale.it/precatecumenato/chi-ci-separera/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: true,
    pentecoste: false,
  },
  {
    titolo: 'Come è bello come dà gioia',
    link:'https://www.cantineocatecumenale.it/precatecumenato/come-e-bello-come-da-gioia/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Davanti agli angeli',
    link:'https://www.cantineocatecumenale.it/precatecumenato/davanti-agli-angeli/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Evenu Shalom',
    link:'https://www.cantineocatecumenale.it/precatecumenato/evenu-shalom-alejem/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Giorno di Riposo',
    link:'https://www.cantineocatecumenale.it/precatecumenato/giorno-di-riposo/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Guardate come è bello',
    link:'https://www.cantineocatecumenale.it/precatecumenato/guardate-come-e-bello/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Ho sperato nel Signore',
    link:'https://www.cantineocatecumenale.it/precatecumenato/ho-sperato-ho-sperato-nel-signore/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: true,
    pentecoste: false,
  },
  {
    titolo: 'Lodate Iddio',
    link:'https://www.cantineocatecumenale.it/precatecumenato/lodate-iddio/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Mi indicherai il sentiero della vita',
    link:'https://www.cantineocatecumenale.it/precatecumenato/mi-indicherai-il-sentiero-della-vita/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Una donna vestita di Sole',
    link:'https://www.cantineocatecumenale.it/precatecumenato/una-donna-vestita-di-sole/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: true,
    aMaria: true,
    natale: true,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Non c\'è in Lui bellezza',
    link:'https://www.cantineocatecumenale.it/precatecumenato/non-ce-in-lui-bellezza/',
    ingresso: false,
    pace: false,
    pane: true,
    vino: false,
    finale: true,
    aMaria: false,
    natale: true,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'O Dio tu sei il mio Dio',
    link:'https://www.cantineocatecumenale.it/precatecumenato/o-dio-tu-sei-il-mio-dio/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'O morte dov\'è la tua vittoria?',
    link:'https://www.cantineocatecumenale.it/precatecumenato/o-morte-dove-la-tua-vittoria/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Pentecoste',
    link:'https://www.cantineocatecumenale.it/precatecumenato/pentecoste/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Per amore dei miei fratelli',
    link:'https://www.cantineocatecumenale.it/precatecumenato/per-amore-dei-miei-fratelli/',
    ingresso: false,
    pace: true,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Andate ed annunziate ai miei fratelli',
    link:'https://www.cantineocatecumenale.it/precatecumenato/andate-ed-annunziate-ai-miei-fratelli/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Dite agli smarriti di cuore',
    link:'https://www.cantineocatecumenale.it/precatecumenato/dite-agli-smarriti-di-cuore/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: true,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Quanto sono amabili le tue dimore',
    link:'https://www.cantineocatecumenale.it/precatecumenato/quanto-sono-amabili-le-tue-dimore/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: true,
    pentecoste: false,
  },
  {
    titolo: 'Se il signore non costruisce la casa',
    link:'https://www.cantineocatecumenale.it/precatecumenato/se-il-signore-non-costruisce-la-casa/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Se oggi ascoltate la Sua voce',
    link:'https://www.cantineocatecumenale.it/precatecumenato/se-oggi-ascoltate-la-sua-voce/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: false,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    
    pentecoste: false,
  },
  {
    titolo: 'Tu sei il più bello',
    link:'https://www.cantineocatecumenale.it/precatecumenato/tu-sei-il-piu-bello/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: true,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: false,
  },
  {
    titolo: 'Un germoglio spunta sul tronco di Jesse',
    link:'https://www.cantineocatecumenale.it/precatecumenato/un-germoglio-spunta-dal-tronco-di-jesse/',
    ingresso: false,
    pace: false,
    pane: false,
    vino: true,
    finale: false,
    aMaria: false,
    natale: true,
    quaresima: false,
    pentecoste: true,
  },
  {
    titolo: 'Vieni dal Libano',
    link:'https://www.cantineocatecumenale.it/precatecumenato/vieni-dal-libano/',
    ingresso: true,
    pace: false,
    pane: false,
    vino: true,
    finale: false,
    aMaria: false,
    natale: false,
    quaresima: false,
    pentecoste: true,
  }
]

export default canti